name: Merge-from-master-into-testing
 
on:
  push:
    branches:
      - master
 
jobs:
  merge:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: 'testing'

 #   - name: Send notification [Always]
 #     uses: neonidian/teams-notify-build-status@v3
 #     if: always()
 #     with:
 #       webhookUrl: ${{ secrets.TEAMS_HOOK1 }}
 #       title: LANDING_MODULE
 #       message: Merge from master into testing has been run
#        titleBackgroundColor: ${{ job.status }}
 #     env:
 #       SHOULD_DISPLAY_VIEW_COMMIT_BUTTON: true
 
    

    - name: Test link
      id: test_link
      run: |
        echo 'Test link'
        ls -la
        pwd
#        gh run view pull_request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 #   - name: Send notification [Failed]
 #     uses: neonidian/teams-notify-build-status@v3
 #     if: ${{ !success() }}                                                          
 #    with:
 #       webhookUrl: ${{ secrets.TEAMS_HOOK1 }}
 #       title: >-
 #         [Repository link](${{ steps.pull_request.outputs }})
#        title: LANDING_MODULE
 #       titleBackgroundColor: ${{ steps.merge_changes.outcome }}
 #       message: >-
 #        Failed merge into testing. Please click the button for more details =>
 #       status: Failure
 #     env:
 #       SHOULD_DISPLAY_VIEW_RUN_BUTTON: true

 #   - name: Send notification [Success]
 #     uses: neonidian/teams-notify-build-status@v3
 #     with:
 #       webhookUrl: ${{ secrets.TEAMS_HOOK }}
 #       title: LANDING_MODULE
 #       titleBackgroundColor: ${{ steps.merge_changes.outcome }}                     
 #       status: ${{ steps.merge_changes.outcome }}                                   
 #       message: >-
 #         Success merge into testing.       
 #     env:
 #       SHOULD_DISPLAY_ACTOR_LABEL: true
 #       SHOULD_DISPLAY_VIEW_RUN_BUTTON: true
 #       SHOULD_DISPLAY_VIEW_COMMIT_BUTTON: true

