name: Merge-from-master-to-testing
 
on:
  push:
    branches:
      - master
 
jobs:
  merge:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Merge changes
#      run: |
#        git fetch
#        git checkout testing
#        git pull --rebase origin master
#        git push origin testing
      uses: devvspaces/merge-branches@v1
      with:
        from_branch: master
        to_branch: testing
