name: Merge-from-master-to-testing
 
on:
  push:
    branches:
      - master
 
jobs:
  merge:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Merge changes
      run: |
        git fetch
        echo "git fetch"
        git checkout --track origin/testing
        echo "git checkout"
        git add 123.txt
        echo "git add"
        git config pull.rebase true
        echo "git config"
        git pull origin master
        echo "git pull"
        git rebase --continue
        echo "git rebase"
        git push origin testing
    
