name: Merge-from-master-into-testing
 
on:
  push:
    branches:
      - master
 
jobs:
  merge:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: 'testing'

    - name: Send notification [Always]
      uses: neonidian/teams-notify-build-status@v3
      if: always()
      with:
        webhookUrl: ${{ secrets.TEAMS_HOOK }}
        title: LANDING_MODULE
        message: Merge from master into testing has been run
#        titleBackgroundColor: ${{ job.status }}
      env:
        SHOULD_DISPLAY_VIEW_COMMIT_BUTTON: true
 
    - name: Merge changes
      id: merge_changes
      run: |
        echo '[========== Run "git status" ===============================]'
        git status
        echo '[========== Run "git pull --rebase origin master" ==========]'
        git pull origin master
        echo '[========== Run "git push origin testing" ==================]'
        git push11 origin testing
        echo '[========== Run "git status" ===============================]'
        git status

    - name: Create pull request
      id: сreate_pull_request
      if: ${{ !success() }}
      run: |
        gh pr create -B testing -H master --title 'Merge "master" into "testing"' --body 'Created by Github Action' --reviewer 1ndreypetrenk0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Send notification [Failed]
      uses: neonidian/teams-notify-build-status@v3
      if: ${{ !success() }}                                                          
      with:
        webhookUrl: ${{ secrets.TEAMS_HOOK }}
        title: >-
          [Repository link](${{ github.server_url }}+$GET_PR_LINK)
#        title: LANDING_MODULE
        GET_PR_LINK: ${{ steps.сreate_pull_request.outcome }}
        titleBackgroundColor: ${{ steps.merge_changes.outcome }}
        message: >-
          Failed merge into testing. Please click the button for more details =>
        status: Failure
      env:
        SHOULD_DISPLAY_VIEW_RUN_BUTTON: true

    - name: Send notification [Success]
      uses: neonidian/teams-notify-build-status@v3
      with:
        webhookUrl: ${{ secrets.TEAMS_HOOK }}
        title: LANDING_MODULE
        titleBackgroundColor: ${{ steps.merge_changes.outcome }}                     
        status: ${{ steps.merge_changes.outcome }}                                   
        message: >-
          Success merge into testing.       
      env:
        SHOULD_DISPLAY_ACTOR_LABEL: true
        SHOULD_DISPLAY_VIEW_RUN_BUTTON: true
        SHOULD_DISPLAY_VIEW_COMMIT_BUTTON: true
