name: Merge-from-master-to-testing
 
on:
  push:
    branches:
      - master
 
jobs:
  merge:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: 'testing'
 
    - name: Merge changes
      id: merge_changes
      run: |
        echo '[========== Run "git status" ===============================]'
        git status
        echo '[========== Run "git pull --rebase origin master" ==========]'
        git pull --rebase origin master
        echo '[========== Run "git push origin testing" ==================]'
        git push origin testing
        echo '[========== Run "git status" ===============================]'
        git statusee

    - name: Send notification [Failed]
      uses: neonidian/teams-notify-build-status@v3
      if: ${{ !success() }}                                                          # For other statuses, see https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions
      with:
        webhookUrl: ${{ secrets.TEAMS_HOOK }}
        message: >-
          Failed Merge to testing - ${{ steps.merge_changes.outcome }}
        status: Failure
      env:
        SHOULD_DISPLAY_VIEW_RUN_BUTTON: true

    - name: Send notification
      uses: neonidian/teams-notify-build-status@v3
      with:
        webhookUrl: |
          ${{ secrets.TEAMS_HOOK }}
        title: LANDING_MODULE
        titleBackgroundColor: ${{ steps.merge_changes.outcome }}                     # Specify title background color. 'merge_changes' is the ID of a step
        status: ${{ steps.merge_changes.outcome }}                                   # Specify what should be displayed in the status label
        message: >-
          TEST ${{ steps.merge_changes.outcome }}       
      env:
        SHOULD_DISPLAY_ACTOR_LABEL: true
        SHOULD_DISPLAY_VIEW_RUN_BUTTON: true
        SHOULD_DISPLAY_VIEW_COMMIT_BUTTON: true
