name: Merge-from-master-to-testing
 
on:
  push:
    branches:
      - master
 
jobs:
  merge:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Merge changes
      run: |
        ls -la
        git fetch
        git checkout testing
        echo "checkout"
        git config pull.rebase false
        echo "pull.rebase"
        git pull origin master
        echo "pull 2"
        git push origin testing
